### ISSUE TITLE
ConfBoilerplate

### ISSUE THREAD

**Issue by zenorocha** [max-mapper/tenconf#1]
Hey @maxogden, you should really take a look at [Conf Boilerplate](http://confboilerplate.com) =]

https://github.com/braziljs/conf-boilerplate/

**Comment by zenorocha** [comment]
By the way, README still in Portuguese but all the code is in English. 
I'm going to translate that soon.

**Comment by max-mapper** [comment]
thanks for the suggestion but a) it's bootstrap b) doesn't have any responsive stuff so it looks bad on mobile

**Comment by zenorocha** [comment]
Hey @maxogden, thanks for your feedback.

It's now responsive! Take a look [confboilerplate.com](http://confboilerplate.com).
Also I've translated all the documentation to English. [See it here](https://github.com/braziljs/conf-boilerplate/blob/master/README-en.md).

It will be awesome if you could share your thoughts about this project.

**Comment by max-mapper** [comment]
Oooooh super nice! And love that it doesn't look like bootstrap anymore!
